### ISSUE TITLE
Adding custom URIVoter no longer works

### ISSUE THREAD

**Issue by oste** [KnpLabs/KnpMenuBundle#149]
I have been using the following code to register my own UriVoter but after updating the bundle it no longer works. What is the proper way to register our own voter services?

```
my.knp_menu.voter:
        class: MY\MenuBundle\Voter\UriVoter
        arguments: [ @service_container ]
        tags:
            - { name: knp_menu.voter }
```
