### ISSUE TITLE
Custom MenuItem

### ISSUE THREAD

**Issue by Mopster** [KnpLabs/KnpMenuBundle#151]
I'm trying to create my own custom MenuItem. The underlying idea is to overwrite the getChildren method in order to lazy load the menuItem's children only when it's the active. So when we have an extensive menu, it only loads the items that need to be visible when using a collapsing menu.

I extended Knp\Menu\MenuItem

``` PHP
class MenuItem extends KnpMenuItem
{
    /**
     * @var \Symfony\Component\EventDispatcher\EventDispatcher
     */
    protected $dispatcher;

    public function getEventDispatcher()
    {
        return $this->dispatcher;
    }

    /**
     * @param EventDispatcher $dispatcher
     */
    public function setEventDispatcher(EventDispatcher $dispatcher)
    {
        $this->dispatcher = $dispatcher;
    }

    public function getChildren()
    {
        return $this->dispatcher->dispatch(Events::CONFIGURE_TOP_MENU_CHILDREN, new ConfigureTopMenuChildrenEvent($this->factory, $this));
    }
}
```

In my services.yml I configured the new MenuItem class

```
    kunstmaan_admin.menu.topmenu:
        class: Kunstmaan\AdminBundle\Helper\Menu\MenuItem
        factory_service: kunstmaan_admin.menubuilder
        factory_method: createTopMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: topMenu }
```

My MenuBuilder contains the following method to create the menu

``` PHP

use Kunstmaan\AdminBundle\Helper\Menu\MenuItem;

...

/**
     * @param Request $request
     *
     * @return ItemInterface
     */
    public function createTopMenu(Request $request)
    {
        $menu = $this->factory->createItem('root');
        $menu->setChildrenAttribute('class', 'nav');

        $settingsMenu = new MenuItem('Setting', $this->factory);
        $settingsMenu->setEventDispatcher($this->dispatcher);
        $menu->addChild($settingsMenu, array('route' => 'KunstmaanAdminBundle_settings'));

        $modulesMenu = new MenuItem('Modules', $this->factory);
        $modulesMenu->setEventDispatcher($this->dispatcher);
        $menu->addChild($modulesMenu, array('route' => 'KunstmaanAdminBundle_modules'));

        $this->dispatcher->dispatch(Events::CONFIGURE_TOP_MENU, new ConfigureTopMenuEvent($this->factory, $menu));

        return $menu;
    }
```

The problem here the 'route' option parameter isn't being used. Meaning the MenuItems link to the current page instead of using the intended route. Using the above code also means the 'current' has also not been set.

When I use the "addChild" method, it uses the route parameter but it creates a default Knp\Menu\MenuItem instead of my own custom MenuItem. And the 'current' variable is set correctly.
