### ISSUE TITLE
Current route and parameters when using render controller

### ISSUE THREAD

**Issue by gaea44** [KnpLabs/KnpMenuBundle#237]
Hi,

here is my problem,
i've a route :

``` yml
admin_updateUser:
    pattern: /user/update/{id}
    defaults: { _controller: adminBundle:User:update}
    requirements:
        id: \d+
```

this page contain a menu which is rendered like this :

mainLayout

``` jinja
{{ render(controller("adminBundle:Common:leftMenu")) }}
```

commonController

``` php
<?php
public function leftMenuAction()
{
    return $this->render('dnAdminBundle:Common:leftMenu.html.twig');
}
```

leftMenu

``` jinja
{{ knp_menu_render('leftMenu', {'template':'adminBundle:Menu:knp_menu.html.twig'}) }}
```

and in my MenuBuilder

``` php
<?php
public function createLeftMenu(Request $request)
{
    var_dump($request->attributes);
}
```

the var_dump result :

```
object(Symfony\Component\HttpFoundation\ParameterBag)#968 (1) {
    ["parameters":protected]=>
    array(4) {
      ["_format"]=>
      string(4) "html"
      ["_locale"]=>
      string(2) "en"
      ["_controller"]=>
      string(29) "dnAdminBundle:Common:leftMenu"
      ["_route_params"]=>
      array(3) {
        ["_format"]=>
        string(4) "html"
        ["_locale"]=>
        string(2) "en"
        ["_controller"]=>
        string(29) "adminBundle:Common:leftMenu"
      }
    }
  }
```

So, how i can get the current route with its parameter and not the route containing the menu?

Thanks.
