### ISSUE TITLE
Add Documentation about default twig renderer options

### ISSUE THREAD

**Issue by h4cc** [KnpLabs/KnpMenuBundle#262]
I am using Twitter Bootstrap and needed to change the "currentClass" to "active" for my whole site and found this quite easy way to do so:

```yaml
# config.yml

parameters:
    knp_menu.renderer.twig.options:
        currentClass: 'active'
```

I think it would be cool to have such a info present in the documentation.
