### ISSUE TITLE
Update documention for Symfony 2.7

### ISSUE THREAD

**Issue by althaus** [KnpLabs/KnpMenuBundle#269]
Hey,

with the Symfony 2.7 the Definition class will trigger deprecation warnings for the factory construction when using menus as a service.

Before:
```
# app/config/services.yml
services:
    app.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory_service: app.menu_builder
        factory_method: createSidebarMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time
```

After:
```
# app/config/services.yml
services:
    app.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory: ["@app.menu_builder", createSidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: sidebar } # Named "sidebar" this time
```

http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_service.html

Took me a while to find the source of the notices (which were printed plaintext in the page and not collected by the profiler in `dev` environment).
