### ISSUE TITLE
Menu undefined when use just menu builder as a service

### ISSUE THREAD

**Issue by GCalmels** [KnpLabs/KnpMenuBundle#284]
Hey,
First, thank you for your awesome bundles.
I am new to Symfony2 and this undefined issue has plagued me for hours. I have followed the KnpMenuBundle documentation for [Creating Menu Builders as Services](http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_builder_service.html) but I have still this error : 
> An exception has been thrown during the rendering of a template ("The menu "main" is not defined.") in AcmePlatformBundle:Layout:header.html.twig at line 22.

And the line 22 is `{{ knp_menu_render('main') }}`

My services.yml :
 ```
#src/Acme/PlatformBundle/Resources/Config/services.yml
app.menu_builder:
        class: Acme\PlatformBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
 ```

If I use [Creating Menu as Services](http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_service.html) it works but it is not recommended by the documentation...

Thank you in advance for your help
