### ISSUE TITLE
Menu as service and Symfony 3.0

### ISSUE THREAD

**Issue by gazouweb** [KnpLabs/KnpMenuBundle#300]
Hi,
I have a problem to render my menu which run perfectly with Symfony 2.7 but not with Symfony 3.0.
my services.yml : 
```
services:
    menu.menu_builder:
        class: MenuBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory", "@doctrine.orm.default_entity_manager"]

    menu.sidebar_menu:
        class: Knp\Menu\MenuItem
        factory_service: ["@menu.menu_builder", createSidebarMenu]
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: sidebar }
```
and i have this message : 

An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Argument 2 passed to Knp\Menu\MenuItem::__construct() must implement interface Knp\Menu\FactoryInterface, none given, called in /var/www/xxxx/var/cache/dev/appDevDebugProjectContainer.php on line 2235 and defined") in ::base.html.twig at line 220.

Help please ...
