### ISSUE TITLE
Symfony3 : How to get KnpMenu in a controller ?

### ISSUE THREAD

**Issue by eved42** [KnpLabs/KnpMenuBundle#316]
Hello everyone,

sorry for this stupid question but I don't find any doc about this.

I followed this symfony tutorial : [Creating Menu Builders as Services](https://symfony.com/doc/master/bundles/KnpMenuBundle/menu_builder_service.html)
Now, how can I get my KnpMenu in a controller ?

For example, I have two methods in my builder : createMainMenu() and createAdminMenu().

```
services:
   app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
```
In my controller, I would like something like this : 
```
// get main menu
$menu = $this->get("app.menu_builder.main");
```
But it doesn't work... I don't know the correct syntax. Can you help me ?

**Comment by stof** [comment]
menus are not defined as services. Use the ``knp_menu.menu_provider`` service to get your menu (it will use the builder internally):

```php
// get main menu
$menu = $this->get('knp_menu.menu_provider')->get('main');
```

**Comment by eved42** [comment]
Ok thanks, it works !
I try to get a particular children in order to set the current state explicitly. But it doesn't work and I have no error.
```
In my controller : 
// get admin menu
$menu = $this->get('knp_menu.menu_provider')->get('admin');
$item = $menu->getChildren('user');
$item['user']->setCurrent(true);
```
$item['user']->isCurrent() returns true but I don't have the "current" css class on the corresponding <li>

Any idea ?

**Comment by stof** [comment]
Well, you are passing your ``$menu`` variable to your template, or are you using the menu provider to build the menu again in the template ? If you rebuild it when using it in the template, you will deal with a different Menu object tree, where you manual change won't be available.

A better solution to achieve your use case is probably to handle this logic in your menu builder based on options, and using the ``knp_menu_get`` argument allowing to pass options to the menu provider.

**Comment by eved42** [comment]
I don't understand very well.
Let me explain to you my project.

I want a simple menu without children, like this : 
- Users (/users/)
- item 2 (/item2/)
- item 3 (/item3/)

When I go to the corresponding route, `users` is set to current, at this point, everything is ok.
But, if I have a url like this : `/users/add` (using the same route), I would like that the current state stay on `users`. Actually it desappears.

That's why, in my `addAction()` function in my `AddUserController.php`, I want to get my admin menu in order to put the current state manually.

So, I created `MenuBuilder.php` with 2 methods (createMainMenu() and createAdminMenu() like in the tutorial) and I use it as a service.
```
<?php

namespace AppBundle\Menu;

use Knp\Menu\FactoryInterface;

class MenuBuilder
{
    private $factory;

    /**
     * @param FactoryInterface $factory
     *
     * Add any other dependency you need
     */
    public function __construct(FactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    public function createAdminMenu(array $options)
    {
        $menu = $this->factory->createItem('root');
        $menu->setChildrenAttribute('class', 'nav nav-sidebar');

        // menu architecture
        $items = array(
          'user' => array(
             'title'  => 'Users management',
             'params' => array(
                'label'    => 'Users',
                'route'    => 'user_show'
             )
          )
       );

       // menu building
       foreach ($items as $name => $item) {
           $menu->addChild($name, $item['params']);
           # ...
       }

       return $menu;
    }
}
```

```
services:
   app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createAdminMenu, alias: admin }
```
Then, I render it in my layout.html.twig
`{{ knp_menu_render('admin') }}`

AddUserController.php
```
class AddUserController extends Controller
{
    /**
     * @Route("/users/add", name="user_add")
     */
    public function addAction(Request $request)
    {
        // get admin menu
        $menu = $this->get('knp_menu.menu_provider')->get('admin');
        $item = $menu->getChildren('user');
        $item['user']->setCurrent(true);
        
        # ...
    }
}
```
What should I change ? Can you explain me in details please. I'm new to Symfony so it's a little bit difficult for me to understand very well, sorry.
