### ISSUE TITLE
Tried to define the service menu as I generated the following error

### ISSUE THREAD

**Issue by jrujano** [KnpLabs/KnpMenuBundle#326]
Attempted to load class "MenuBuilder" from namespace "AdminBundle\Menu".
Did you forget a "use" statement for another namespace?

src/AdminBundle/Menu/Builder.php
```php
<?php

namespace AdminBundle\Menu;

use Knp\Menu\FactoryInterface;

class MenuBuilder
{
    private $factory;

/**
 * @param FactoryInterface $factory
 *
 * Add any other dependency you need
 */
public function __construct(FactoryInterface $factory)
{
    $this->factory = $factory;
}

public function createMainMenu(array $options)
{
    $menu = $this->factory->createItem('root');

    $menu->addChild('Empresa', array('route' => 'admin_empresa_index'));
    // ... add more children

    return $menu;
}

}
```

/app/config/services.yml
```
services:
    app.menu_builder:
        class: AdminBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main } 
```

app/Resources/views/base.html.twig
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}{% endblock %}
        <link rel="icon" type="image/x-icon" href="{{ asset('favicon.ico') }}" />
    </head>
    <body>
         {{ knp_menu_render('main') }}
        {% block page_content %}{% endblock %}
    {% block javascripts %}{% endblock %}
</body>


</html>
```
