### ISSUE TITLE
Missing documentation about autowiring

### ISSUE THREAD

**Issue by garak** [KnpLabs/KnpMenuBundle#368]
[Current docs](http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_builder_service.html) are still showing the old approach (e.g. the one working with Symfony < 3.4).
We need to cover also the new autowiring features of Symfony 3.4/4.0

**Comment by stof** [comment]
Well, this doc is perfectly valid today. The only change with autowiring is that you can remove the definition of the constructor arguments (the FactoryInterface implementation can be injected by the autowiring).

I have a new feature in my TODO list which will make it much easier to use the library in alongside autoconfiguration. But it is not there yet

**Comment by garak** [comment]
I know the docs are still valid, but I think it's a pity to miss showing the new features. I think docs should be expanded to cover both options, the old ones and the new ones.
Other doubts: is there currently a way to avoid declaring a menu? For example, this is my current declaration:
```yaml
    app.menu.main:
        class: Knp\Menu\MenuItem
        factory: ['@App\Menu\Builder', createMenu]
        tags:
            - { name: knp_menu.menu, alias: main }
```
Can I exploit somehow the autowiring/autoconfigure?

**Comment by poolerMF** [comment]
+1

**Comment by stof** [comment]
@garak only in my head. I know exactly how I want this to work for autoconfiguration, but I have not written the code yet (I need a few hours available for that but I'm quite busy these days)

**Comment by garak** [comment]
Sorry for bumping (I know it's not really nice), but I was wondering if there are some news here.

**Comment by vctls** [comment]
This works, apparently:
```yml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  AppBundle\Menu\:
    resource: '../../src/AppBundle/Menu/*'

  AppBundle\Menu\Builder:
    tags:
      - { name: knp_menu.menu_builder, method: mainMenu, alias: main }
```
```twig
{{ knp_menu_render('main', { 'template': 'knpmenu/knp_menu.html.twig' }) }}
```
But I couldn't get it working without the tag. If I try to render the menu like this
```twig
{{ knp_menu_render('AppBundle:Builder:mainMenu', { 'template': 'knpmenu/knp_menu.html.twig' }) }}
```
`BuilderAliasProvider` tries to instanciate it without any of its dependencies.
