### ISSUE TITLE
Provide autowiring for MenuProviderInterface

### ISSUE THREAD

**Issue by Soullivaneuh** [KnpLabs/KnpMenuBundle#384]
Current error:

```
Cannot autowire service "AppBundle\Menu\SidebarMenuBuilder": argument "$menuProvider" of method "__construct()" references interface "Knp\Menu\Provider\MenuProviderInterface" but no such service exists. You should maybe alias this interface to one of these existing services: "knp_menu.menu_provider.chain", "knp_menu.menu_provider.lazy", "knp_menu.menu_provider.builder_alias", "sonata.admin.menu.group_provider". Did you create a class that implements this interface?
```

Current workaround:

```yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Knp\Menu\Provider\MenuProviderInterface: '@knp_menu.menu_provider'
```
