### ISSUE TITLE
Can't extract Menu label with JMSTranslation

### ISSUE THREAD

**Issue by picks44** [KnpLabs/KnpMenuBundle#393]
HI,

I'm using JMSTranslationBundle (1.4.3)  on a Symfony 3.4 project to extract and manage my translation, but it seems that it does not extract the menu labels from KNPMenu (2.2.1) when set up as a service... Can you help please?

Here is my JMS config 

```
jms_translation:
    configs:
        app:
            dirs: ["%kernel.root_dir%/Resources/views", "%kernel.root_dir%/../src"]
            output_dir: "%kernel.root_dir%/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
```

And my Menu.php service

```
<?php

namespace AppBundle\Service;

use Knp\Menu\FactoryInterface;

/**
 * Class Menu
 * @package AppBundle\Menu
 */
class Menu
{
    /**
     * @var FactoryInterface
     */
    private $factory;

    /**
     * Menu constructor.
     * @param FactoryInterface $factory
     */
    public function __construct(FactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    /**
     * @return \Knp\Menu\ItemInterface
     * @throws \InvalidArgumentException
     */
    public function createMainMenu()
    {
        $menu = $this->factory->createItem('root');
        $menu->setChildrenAttribute('class', 'navbar-nav ml-auto');

        $menu->addChild('menu.home', [
            'route' => 'index'
        ])->setAttribute('class', 'nav-item')->setExtra('translation_domain', 'menu');
        $menu['menu.home']->setLinkAttribute('class', 'nav-link');

        $menu->addChild('menu.projects', [
            'route' => 'projects',
            'extras' => [
                'routes' => [
                    [
                        'route' => 'project'
                    ],
                ],
            ],
        ])->setAttribute('class', 'nav-item')->setExtra('translation_domain', 'menu');
        $menu['menu.projects']->setLinkAttribute('class', 'nav-link');

        $menu->addChild('menu.contact', [
            'route' => 'contact'
        ])->setAttribute('class', 'nav-item')->setExtra('translation_domain', 'menu');
        $menu['menu.contact']->setLinkAttribute('class', 'nav-link');

        return $menu;
    }
}

```

I cannot get the keys for `menu.home`, `menu.projects`, `menu.contact`
