### ISSUE TITLE
SF 4.3 - Voters - theirs order and auto-registration as service

### ISSUE THREAD

**Issue by sabat24** [KnpLabs/KnpMenuBundle#411]
1.

I created new Voter in _src\Menu\Voter_ directory. I was surprised that I didn't have to register that voter as a service in services.yaml. Voter just started to work without any other action from my side. Is it normal behaviour because I used _menu_ directory name which is the directory of the bundle? 

2.

My Voter was added before default one to the matcher's voters array. I would like to change the order of voters that my voter would be the last one. Is it possible? If not can I (I mean is it good solution) just create new class and extends _Knp\Menu\Matcher\Matcher_ class to overwrite constructor and reverse order of already added voters?

**Comment by stof** [comment]
if you autoconfigure your services (which is the default behavior in a Symfony 4 app based on the Flex skeleton), a service implementing the VoterInterface will automatically be tagged as `knp_menu.voter`. This is why it is working without extra config. It is not related to the namespace of the class.

Voters can have a priority to control their order. But that will require tagging them as voter explicitly (the autoconfigured tag does not specify a priority, which makes it fallback to `0`, as done in Symfony core).
Extending the Matcher and reversing the order of voters is not the supported way of doing that (and would break the lazy-loading of voters performed by the injected iterator).

**Comment by sabat24** [comment]
Thank you for clarification.

I'm not sure if my further concern is related strictly to that bundle or to Symfony 4 architecture. However based on what you have described, I have to manually tagged voters and provide priority order. However when I tagged voters manually in services.yaml my custom voter in matcher is duplicated. 

```yaml
app.voter.route:
    class: Knp\Menu\Matcher\Voter\RouteVoter
    arguments: [ '@request_stack' ]
    tags:
      - { name: knp_menu.voter, priority: 0 }
  app.voter.parent:
    class: App\Menu\Voter\RequestParentRouteVoter
    arguments: [ '@request_stack' ]
    tags:
      - { name: knp_menu.voter, priority: 1 }
```

When matcher is initialized there are 3 voters:

App\Menu\Voter\RequestParentRouteVoter <- custom voter
App\Menu\Voter\RequestParentRouteVoter <- custom voter
Knp\Menu\Matcher\Voter\RouteVoter <- default voter

Am I doing something wrong?
