### ISSUE TITLE
Menu undefined when use as a service

### ISSUE THREAD

**Issue by AStew8** [KnpLabs/KnpMenuBundle#86]
I am new to Symfony2 and this undefined issue has plagued me for hours.  I have followed the KnpMenuBundle and the KnpMenu documents to build my main navigation menu which is called out in my base.html.twig template with `{{ knp_menu_render('main') }}`.  I am using Symfony 2.0.6 and have the latest of the KnpMenu and bundle.

My menu builder from my SiteBundle is as follows (I changed all my routes during troubleshooting to see if that was causing menu to be undefined):

``` php
<?php
// src/NEGL/SiteBundle/Menu/MenuBuilder.php

namespace NEGL\SiteBundle\Menu;

use Knp\Menu\FactoryInterface;
use Symfony\Component\HttpFoundation\Request;

class MenuBuilder
{
    private $factory;

    /**
     * @param FactoryInterface $factory
     */
    public function __construct(FactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    public function createMainMenu(Request $request)
    {
        $menu = $this->factory->createItem('root');
        $menu->setCurrentUri($request->getRequestUri());

        $menu->addChild('Home', array('uri' => '#homepage'));
        $menu->addChild('Events', array('uri' => '#events'));
        $menu->addChild('Community', array('uri' => '#community'));
        $menu->addChild('Files', array('uri' => '#files'));
        $menu->addChild('Partners', array('uri' => '#partners'));
        $menu->addChild('Support', array('uri' => '#support'));
        $menu->addChild('Servers', array('uri' => '#servers'));
        $menu->addChild('FAQ', array('uri' => '#faq'));
        $menu->addChild('About', array('uri' => '#about'));
        $menu->addChild('Jobs', array('uri' => '#job_openings'));


        return $menu;
    }
```

here is the service:

``` yaml
#  src/NEGL/SiteBundle/Resources/Config/services.yml
services:
    negl_site.menu_builder:
        class: NEGL\SiteBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    negl_site.menu.main:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: negl_site.menu_builder
        factory_method: createMainMenu
        arguments: ["@request"]
        scope: request # needed as we have the request as a dependency here
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
```

 in my app/config/config.yml:

``` yaml
knp_menu:
    twig: true
```

I cannot seem to figure out what is the issue.  I am sorry if this type of issue should have been posted to the Symfony2-User Group.  Thank you for your help in advance.  It is probably something I am just overlooking.
