### ISSUE TITLE
As service: The menu “main” is not defined exception in rendering template

### ISSUE THREAD

**Issue by hartleypool** [KnpLabs/KnpMenuBundle#89]
I'm using Symfony2 with the KnpMenuBundle installed as submodules and using the service configuration method.

When calling the page with the menu in the layout using:

`{{ knp_menu_render('main') }}`

I get the error:

   `An exception has been thrown during the rendering of a template ("The menu "main" is not defined.") in CCGlobalBundle::layout.html.twig`

My services.yml file (is parsed in the load() method of the CCGlobalExtension.php bundle class) seems to be being called as intentional errors in it cause further code errors:

```
# src/CC/GlobalBundle/Resources/Config/services.yml
services:
cc_global.menu_builder:
    class: CC\GlobalBundle\Menu\MenuBuilder
    arguments: ["@knp_menu.factory"]

cc_global.menu.main:
    class: Knp\Menu\MenuItem # the service definition requires setting the class
    factory_service: cc_global.menu_builder
    factory_method: createMainMenu
    arguments: ["@request"]
    scope: request # needed as we have the request as a dependency here
    tags:
        - { name: knp_menu.menu, alias: main } 
```

And my main /app/config/config.yml file contains the knp_menu: directive:

``` knp_menu:
twig: 
    template: knp_menu.html.twig
templating: false # if true, enables the helper for PHP templates
default_renderer: twig # The renderer to use, list is also available by default 
```

Does anyone know what might be causing this?
